services:
  web:
    image: "horsecatdog/bedrock:latest"
    build:
        context: .
        dockerfile: images/web/Dockerfile
        args:
          PROJECTS_DIR: ${PROJECTS_DIR}
          PROJECT: ${PROJECT}
          THEME: ${THEME}
    depends_on:
      - db
    ports:
      - "${LOCAL_PORT}:80"

  db:
    image: "mariadb:latest"
